bulky/Areas/Admin/Controllers/UserController.cs
using bulky.DataAccess.Data;
using bulky.Models.Models;
using Bullky.DataAccess.Repository;
using Bullky.DataAccess.Repository.IRepository;
using Bullky.Models.Models;
using Microsoft.AspNetCore.Mvc;

namespace bulky.Areas.Admin.Controllers
{
	public class UserController : Controller
	{
		private readonly ApplicationDbContext _db;
		public UserController(ApplicationDbContext db)
		{
			_db = db;
		}
		public IActionResult Index()
		{
			var ObjUsersList = _db.users.ToList();
			return View(ObjUsersList);
		}

		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			Users? UserFromDb = _db.users.Find(id);
			if (UserFromDb == null)
			{
				return NotFound();
			}
			return View(UserFromDb);
		}

		[HttpPost]
		[ActionName("Delete")]
		public IActionResult DeletePOST(int? id)
		{
			if (id == null || id == 0) { return NotFound(); }
			Users? obj = _db.users.Find(id); 
			if (obj == null) { return NotFound(); }
			_db.users.Remove(obj);
			_db.SaveChanges();
			TempData["success"] = "Category Deleted Successfully";
			return RedirectToAction("index");

		}
	}
}

bulky/Areas/Customer/Controllers/CustomerHomeController.cs
using bulky.DataAccess.Data;
using bulky.DataAccess.Migrations;
using Bullky.DataAccess.Repository.IRepository;
using Bullky.Models.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;

namespace bulky.Areas.Customer.Controllers
{
	public class CustomerHomeController : Controller
	{
		IUnitOfWork _UnitOfWork { get; set; }
		private readonly ApplicationDbContext _db;
		public CustomerHomeController(IUnitOfWork unitOfWork, ApplicationDbContext db)
		{
			_UnitOfWork = unitOfWork;
			_db = db;
			
		}
		public IActionResult Index(int userId)
		{
			IEnumerable<Product> ProductList =_UnitOfWork.Product.GetAll(includeproperties:"Category");
			var viewModel = new { ProductList = ProductList, UserId = userId };

			return View(viewModel);
		}

		public IActionResult Details(int productId, int userId)
		{
			Product product = _UnitOfWork.Product.Get(u=>u.Id == productId, includeproperties: "Category");
			var viewModel = new { product = product, UserId = userId, productId= productId };
			ViewBag.ProductId = productId;
			ViewBag.UserId = userId;
			return View(viewModel);
		}
		public IActionResult AddCart(int Quantity, int productId, int UserId)
		{
            
			Cart cart = Cart.GetInstance();
            cart=_db.carts.Include(c => c.Items).FirstOrDefault(u => u.UserId == UserId);

			if (cart == null)
			{

				cart = Cart.GetInstance();
				cart.UserId = UserId;
				cart.Items = new List<CartItem>();
				

				_db.carts.Add(cart);
				_db.SaveChanges(); 
			}

			// Retrieve the cart again to ensure that the Items collection is loaded
			cart = _db.carts.Include(c => c.Items).FirstOrDefault(u => u.UserId == UserId);

			if (cart != null)
			{
				CartItem item = new CartItem
				{
					Product = _db.products.FirstOrDefault(p => p.Id == productId),
					Quantity = Quantity
				};

				// Add the item to the cart
				_db.cartItems.Add(item);
				_db.SaveChanges();
				cart.Items.Add(item);
				_db.carts.Update(cart);
				// Save changes to the database
				_db.SaveChanges();
			}
			return NoContent();
		}
	}
}

bulky/Areas/Customer/Controllers/UserInfoController.cs
using bulky.DataAccess.Data;
using Bullky.DataAccess.Repository;
using Bullky.Models.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace bulky.Areas.Customer.Controllers
{
	public class UserInfoController : Controller
	{
		private readonly ApplicationDbContext _db;
        private IWebHostEnvironment _webHostEnvironment;

        public UserInfoController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
		{
			_db = db;
            _webHostEnvironment = webHostEnvironment;
		}
		public IActionResult Index(int userId)
		{
			Users user= _db.users.FirstOrDefault(u=>u.Id == userId);
			return View(user);
		}
		public IActionResult Update(int id)
		{
            Users user = _db.users.FirstOrDefault(u => u.Id == id);
            return View(user);
		}
		[HttpPost]
		public IActionResult Update(Users user,IFormFile file) 
		{
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {

                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRootPath, @"images\product");
                    if (!string.IsNullOrEmpty(user.ImageUrl))
                    {
                        var oldPath = Path.Combine(wwwRootPath, user.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldPath))
                        {
                            System.IO.File.Delete(oldPath);
                        }
                    }
                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {

                        file.CopyTo(fileStream);
                    }

                    user.ImageUrl = @"\images\product\" + fileName;
                    user.Money = 50000;
                    _db.Update(user);
                    _db.SaveChanges();
                }
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            return View();
		}
		
        }
}

bulky/Areas/Customer/Views/UserInfo/Index.cshtml
@using Bullky.Models.Models
@model Users
<form method="post">
    <div class="card shadow border-0 mt-4">
        <div class="card-header bg-secondary bg-gradient text-light py-4">
            <div class="row">
                <div class="col-12 text-center">
                    <h3 class="text-white text-uppercase">@Model.UserName</h3>
                    
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="py-3">
                <div class="row">
                    <div class="col-6 col-md-2 offset-lg-1 pb-1">
                        <a asp-action="Index" asp-controller="CustomerHome" asp-route-UserId="@Model.Id" class="btn btn-outline-primary bg-gradient mb-5 fw-semibold btn-sm text-uppercase">
                            <small>Back to home</small>
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-lg-3 offset-lg-1 text-center mb-3">
                        <img src="@Model.ImageUrl" width="100%" class="rounded" />
                    </div>
                    <div class="col-12 col-lg-6 offset-lg-1">

                        

                        <div class="row ps-2">
                            <h6 class="text-dark   pb-2">
                                E-mail: @Model.Email
                                
                            </h6>
                        </div>
                        <div class="row ps-2">
                            <h6 class="text-dark   pb-2">
                                Ssn: @Model.Ssn

                            </h6>
                        </div>
                        <div class="row ps-2">
                            <h6 class="text-dark   pb-2">
                                Phone: @Model.PhoneNumber

                            </h6>
                        </div>
                        <div class="row ps-2">
                            <h6 class="text-dark   pb-2">
                                Credit card: @Model.CreditCardNum

                            </h6>
                        </div>
                        <div class="row ps-2">
                            <p class="text-dark   pb-2">
                               Bio : @Model.Bio

                            </p>
                        </div>
                        
                        
                        
                        
                        
                        <div class="row">
                            <div class="col-12 col-md-6 pb-1">
                                <a  asp-action="Update" asp-controller="UserInfo" asp-route-id="@Model.Id" class="btn btn-primary bg-gradient  w-100 py-2 text-uppercase fw-semibold">
                                    Edit User
                                </a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</form>

bulky/Areas/Customer/Views/UserInfo/Update.cshtml
@using Bullky.Models.Models
@model Users
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-light"> "Update" : "Create" User</h2>
            </div>
        </div>
    </div>

    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="ImageUrl" hidden />
            <div class="mb-3 p-1">
                <label class="p-1" asp-for="UserName" ></label>
                <input type="text" class="form-control" asp-for="UserName" />
                <span class="text-danger"></span>
            </div>

            <div class="mb-3 p-1">
                <label class="p-1" asp-for="@Model.Password"></label>
                <input type="text" class="form-control" asp-for="@Model.Password" />
                <span  class="text-danger"></span>
            </div>

            <div class="mb-3 p-1">
                <label class="p-1" asp-for="@Model.Bio"></label>
                <input type="text" class="form-control" asp-for="@Model.Bio" />
                <span  class="text-danger"></span>
            </div>

            <div class="mb-3 p-1">
                <label class="p-1" asp-for="@Model.Email"></label>
                <input type="email" class="form-control" asp-for="@Model.Email" />
                <span  class="text-danger"></span>
            </div>
            <div class="mb-3 p-1">
                <label class="p-1" asp-for="Ssn"></label>
                <input type="text" class="form-control" asp-for="Ssn" />
                <span class="text-danger"></span>
            </div>
            <div class="mb-3 p-1">
                <label class="p-1" asp-for="@Model.PhoneNumber"></label>
                <input type="text" class="form-control" asp-for="@Model.PhoneNumber" />
                <span class="text-danger"></span>
            </div>
            <div class="mb-3 p-1">
                <label class="p-1" asp-for="@Model.CreditCardNum"></label>
                <input type="text" class="form-control" asp-for="@Model.CreditCardNum" />
                <span class="text-danger"></span>
            </div>

            <div class="mb-3 p-1">
                <label asp-for="ImageUrl" class="p-1" ></label>
                <input type="file" name="file" asp-for="ImageUrl" class="form-control" />
                <!-- Display the existing image if available -->
                @* @if (!string.IsNullOrEmpty(Model.ImageUrl))
                {
                    <img src="@Model.ImageUrl" width="50%" style="border-radius:5px; border: 1px solid #bbb9b9" />
                } *@
                <span  class="text-danger"></span>
            </div>

            <!-- Additional form controls for other user properties -->

            <div class="row">
                <div class="col-6 col-md-3">
                    <button type="submit"  class="btn btn-dark form-control">Update</button>
                </div>
                <div class="col-6 col-md-3">
                    <a
                        class="btn btn-outline-secondary form-control" asp-controller="User" asp-action="Index">
                        Back To List
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>