bulky/Areas/Admin/Controllers/HomeAdminController.cs
using bulky.Models.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace bulky.Areas.Admin.Controllers
{
	
	public class HomeAdminController : Controller
	{
		private readonly ILogger<HomeAdminController> _logger;

		public HomeAdminController(ILogger<HomeAdminController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

bulky/Areas/Admin/Controllers/ProductController.cs
using bulky.DataAccess.Data;
using bulky.Models.Models;
using Bullky.DataAccess.Repository.IRepository;
using Bullky.Models.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.IO;


namespace bulky.Areas.Admin.Controllers
{
    //[Area("Customer")]
	public class ProductController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
		private IWebHostEnvironment _webHostEnvironment;

		public ProductController(IUnitOfWork db,IWebHostEnvironment webHostEnvironment)
        {
            unitOfWork = db;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var ObjCategoriesList = unitOfWork.Product.GetAll(includeproperties:"Category").ToList();
            return View(ObjCategoriesList);
        }
        public IActionResult Upsert(int? id)
        {
            IEnumerable<SelectListItem> CategoryList = unitOfWork.Category.GetAll().
               Select(u => new SelectListItem
               {
                   Text = u.Name,
                   Value = u.Id.ToString(),
               });
            ProductVM productVM = new ProductVM
            {
                CategoryList = CategoryList,
                Product = new Product(),
            };

			if (id == null || id == 0)
			{
			    return View(productVM);
			}
            else
            {
				productVM.Product = unitOfWork.Product.Get(u=>u.Id == id);
				return View(productVM);
			}


		}

        [HttpPost]
        public IActionResult Upsert(ProductVM productVM , IFormFile? file)
		{
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {

                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRootPath, @"images\product");
                    if(!string.IsNullOrEmpty(productVM.Product.ImageUrl)) {
                        var oldPath =Path.Combine(wwwRootPath, productVM.Product.ImageUrl.TrimStart('\\'));
                        if(System.IO.File.Exists(oldPath))
                        {
                            System.IO.File.Delete(oldPath);
                        }
                    }
					using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create)){

                        file.CopyTo(fileStream);
                    }

					productVM.Product.ImageUrl = @"\images\product\" + fileName;
				}
                if(productVM.Product.Id==0)
                {
				unitOfWork.Product.Add(productVM.Product);

                }
                else
                {
                    unitOfWork.Product.Update(productVM.Product);
                }
                unitOfWork.Save();
                TempData["success"] = "Product Added Successfully";
                return RedirectToAction();
            }
            else
            {
				productVM.CategoryList = unitOfWork.Category.GetAll().
			   Select(u => new SelectListItem
			   {
				   Text = u.Name,
				   Value = u.Id.ToString(),
			   });
				
            return View(productVM);
			}
        }

       

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Product? ProductFromDb = unitOfWork.Product.Get(u => u.Id == id);
            if (ProductFromDb == null)
            {
                return NotFound();
            }
            return View(ProductFromDb);
        }

        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            if (id == null || id == 0) { return NotFound(); }
            Product? obj = unitOfWork.Product.Get(u => u.Id == id);
            if (obj == null) { return NotFound(); }
            unitOfWork.Product.Remove(obj);
            unitOfWork.Save();
            TempData["success"] = "Product Deleted Successfully";
            return RedirectToAction("index");

        }

    }
}

bulky/Areas/Admin/Views/Product/Delete.cshtml
@model Product

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-light ">Delet Product</h2>
			</div>
		</div>
	</div>

	<div class="card-body p-4">
		<form method="post">
	<div class="border p-3 pt-4">
		
		<div asp-validation-summary="All"></div>
		<input asp-for="Id" hidden />
				<div class="mb-3 p-1">
					<label class="p-1">Product Title</label>
					<input asp-for=Title type="text" disabled class="form-control" />
				</div>

				<div class="mb-3 p-1">
					<label class="p-1">Description</label>
					<textarea asp-for=Description type="email" disabled class="form-control" ></textarea>

				</div>
				
				<div class="mb-3 p-1">
					<label class="p-1">Author</label>
					<input asp-for=Author type="text" disabled class="form-control" />

				</div>
				<div class="mb-3 p-1">
					<label class="p-1">List Price</label>
					<input asp-for=ListPrice type="number" disabled class="form-control" />

				</div>
				<div class="mb-3 p-1">
					<label class="p-1">Price</label>
					<input asp-for=Price type="number" disabled class="form-control" />

				</div>
				
				

		<div class="row">

			<div class="col-6 col-md-3">
				<button type="submit" asp-action="Delete" class="btn btn-danger form-control">Delete</button>
			</div>

			<div class="col-6 col-md-3">
				<a class="btn btn-outline-secondary form-control" asp-controller="Product" asp-action="Index">
					Back To List
				</a>
			</div>

		</div>

	</div>

</form>
	</div>
</div>

bulky/Areas/Admin/Views/Product/Index.cshtml
@model List<Product>
<partial name="_Notification"/>
@await Html.PartialAsync("_Notification")


<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-light ">Product List</h2>
			</div>
		</div>
	</div>

	<div class="card-body p-4">
		<div class="container">

			<div class="row  pb-3">
				<div class="col-2 text-end">
					<a class="btn btn-primary" asp-controller="HomeAdmin" asp-action="Index">
						back to home
					</a>
				</div>
				
				<div class="col-12 text-end">
					<a class="btn btn-primary" asp-controller="Product" asp-action="Upsert">
						<i class="bi bi-plus-circle-dotted"></i> Create New Product
					</a>
				</div>
			</div>

			<table class="table table-bordered  table-striped">
				<thead>
					<tr>
						<th>Product name</th>
						<th>Price</th>
						<th>Brand</th>
						<th>Category</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					@foreach (var obj in Model)
					{
						<tr>
							<td>@obj.Title</td>
							<td>@obj.Price</td>
							<td>@obj.Author</td>
							<td>@obj.Category.Name</td>
							<td>
								<div class="w-75 btn-group" role="group">
									<a asp-controller="Product" asp-action="Upsert" asp-route-id="@obj.Id" class=" btn btn-secondary mx-2">
										<i class="bi bi-pencil-square"></i> Edit
									</a>
									<a asp-controller="Product" asp-action="Delete" asp-route-id="@obj.Id" class=" btn btn-danger mx-2">
										<i class="bi bi-trush-fill"></i> Delete
									</a>
								</div>
							</td>
						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>
</div>

bulky/Areas/Admin/Views/Product/Upsert.cshtml
@model ProductVM
@using Microsoft.AspNetCore.Mvc.Rendering;


<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-light">@(Model.Product.Id!=0?"Update":"Create") Product</h2>
			</div>
		</div>
	</div>
	
	<div class="card-body p-4">
		<form method="post" class="row" enctype="multipart/form-data">
			<input asp-for="Product.Id" hidden />
			<input asp-for="Product.ImageUrl" hidden />

			<div class="row">
				<div class="col-10">
					<div class="border p-3 ">

						<div asp-validation-summary="All"></div>

						<div class="mb-3 p-1">
							<label class="p-1">Product Title</label>
							<input asp-for=Product.Title type="text" class="form-control" />
							<span asp-validation-for="Product.Title" class="text-danger"></span>
						</div>

						<div class="mb-3 p-1">
							<label class="p-1">Description</label>
							<textarea asp-for=Product.Description type="email" class="form-control"></textarea>
							<span asp-validation-for="Product.Description" class="text-danger"></span>

						</div>
						
						<div class="mb-3 p-1">
							<label class="p-1">Author</label>
							<input asp-for=Product.Author type="text" class="form-control" />
							<span asp-validation-for="Product.Author" class="text-danger"></span>

						</div>
						<div class="mb-3 p-1">
							<label class="p-1">List Price</label>
							<input asp-for=Product.ListPrice type="number" class="form-control" />
							<span asp-validation-for="Product.ListPrice" class="text-danger"></span>

						</div>
						<div class="mb-3 p-1">
							<label class="p-1">Price</label>
							<input asp-for=Product.Price type="number" class="form-control" />
							<span asp-validation-for="Product.Price" class="text-danger"></span>

						</div>
						
						
						<div class="mb-3 p-1">
							<label class="p-1" asp-for="Product.CategoryId"></label>
							<select asp-for=Product.CategoryId asp-items="@Model.CategoryList" class="form-select">
								<option>-- select category --</option>
							</select>

							<span asp-validation-for="Product.CategoryId" class="text-danger"></span>

						</div>
						<div class="mb-3 p-1">
							<label class="p-1" asp-for="Product.ImageUrl"></label>
							<input asp-for=Product.ImageUrl type="file" name="file" class="form-control" />
@* 							<span asp-validation-for="Product.ImageUrl" class="text-danger"></span>
 *@
						</div>


						<div class="row">

							<div class="col-6 col-md-3">
								<button type="submit" class="btn btn-dark form-control">Create</button>
							</div>

							<div class="col-6 col-md-3">
								<a class="btn btn-outline-secondary form-control" asp-controller="Product" asp-action="Index">
									Back To List
								</a>
							</div>

						</div>

					</div>
				</div>
				<div class="col-2">
					<img src="@Model.Product.ImageUrl" width="100%"
						 style="border-radius:5px; border: 1px solid #bbb9b9" />

				</div>
			</div>
			
				



					

		</form>
	</div>
</div>