bulky/Areas/Admin/Controllers/CategoryController.cs
using bulky.DataAccess.Data;
using bulky.Models.Models;
using Bullky.DataAccess.Repository;
using Bullky.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace bulky.Areas.Admin.Controllers
{

	public class CategoryController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        public CategoryController(IUnitOfWork db)
        {
            unitOfWork = db;
        }
        public IActionResult Index()
        {
            var ObjCategoriesList = unitOfWork.Category.GetAll().ToList();
            return View(ObjCategoriesList);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category obj)
        {
            if (obj.Name == obj.Order.ToString())
            {
                ModelState.AddModelError("name", "the dispaly order cannot exactly match the name");
            }
            if (obj.Name.ToLower() == "test")
            {
                ModelState.AddModelError("name", "test is invalid category name");
            }
            if (ModelState.IsValid)
            {
				unitOfWork.Category.Add(obj);
				unitOfWork.Save();
				TempData["success"] = "Category Added Successfully";
				return RedirectToAction();
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? CategoryFromDb = unitOfWork.Category.Get(u => u.Id == id);
            if (CategoryFromDb == null)
            {
                return NotFound();
            }
            return View(CategoryFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Category obj)
        {
            if (obj.Name == obj.Order.ToString())
            {
                ModelState.AddModelError("name", "the dispaly order cannot exactly match the name");
            }
            if (obj.Name.ToLower() == "test")
            {
                ModelState.AddModelError("name", "test is invalid category name");
            }
            if (ModelState.IsValid)
            {
				unitOfWork.Category.Update(obj);
				unitOfWork.Save();
				TempData["success"] = "Category Updated Successfully";

				return RedirectToAction("index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? CategoryFromDb = unitOfWork.Category.Get(u => u.Id == id);
            if (CategoryFromDb == null)
            {
                return NotFound();
            }
            return View(CategoryFromDb);
        }

        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            if (id == null || id == 0) { return NotFound(); }
            Category? obj = unitOfWork.Category.Get(u => u.Id == id);
            if (obj == null) { return NotFound(); }
			unitOfWork.Category.Remove(obj);
			unitOfWork.Save();
			TempData["success"] = "Category Deleted Successfully";

			return RedirectToAction("index");

        }
		

	}
}

bulky/Areas/Admin/Controllers/HomeAdminController.cs
using bulky.Models.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace bulky.Areas.Admin.Controllers
{
	
	public class HomeAdminController : Controller
	{
		private readonly ILogger<HomeAdminController> _logger;

		public HomeAdminController(ILogger<HomeAdminController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

bulky/Areas/Admin/Controllers/UserController.cs
using bulky.DataAccess.Data;
using bulky.Models.Models;
using Bullky.DataAccess.Repository;
using Bullky.DataAccess.Repository.IRepository;
using Bullky.Models.Models;
using Microsoft.AspNetCore.Mvc;

namespace bulky.Areas.Admin.Controllers
{
	public class UserController : Controller
	{
		private readonly ApplicationDbContext _db;
		public UserController(ApplicationDbContext db)
		{
			_db = db;
		}
		public IActionResult Index()
		{
			var ObjUsersList = _db.users.ToList();
			return View(ObjUsersList);
		}

		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			Users? UserFromDb = _db.users.Find(id);
			if (UserFromDb == null)
			{
				return NotFound();
			}
			return View(UserFromDb);
		}

		[HttpPost]
		[ActionName("Delete")]
		public IActionResult DeletePOST(int? id)
		{
			if (id == null || id == 0) { return NotFound(); }
			Users? obj = _db.users.Find(id); 
			if (obj == null) { return NotFound(); }
			_db.users.Remove(obj);
			_db.SaveChanges();
			TempData["success"] = "Category Deleted Successfully";
			return RedirectToAction("index");

		}
	}
}

bulky/Areas/Admin/Views/User/Delete.cshtml
@model Users

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-light ">Delet Category</h2>
			</div>
		</div>
	</div>

	<div class="card-body p-4">
		<form method="post">
	<div class="border p-3 pt-4">
		
		<div asp-validation-summary="All"></div>
		<input asp-for="Id" hidden />
		<div class="mb-3 p-1">
					<label class="p-1">User Name</label>
			<input asp-for=UserName type="text" class="form-control " disabled />
		</div>

		<div class="mb-3 p-1">
			<label class="p-1">E-mail</label>
			<input asp-for=Email type="text" class="form-control " disabled />
		</div>

		<div class="mb-3 p-1">
			<label class="p-1">Phone Number</label>
			<input asp-for=PhoneNumber type="text" class="form-control " disabled />
		</div>

		<div class="row">

			<div class="col-6 col-md-3">
				<button type="submit" asp-action="Delete" class="btn btn-danger form-control">Delete</button>
			</div>

			<div class="col-6 col-md-3">
				<a class="btn btn-outline-secondary form-control" asp-controller="Category" asp-action="Index">
					Back To List
				</a>
			</div>

		</div>

	</div>

</form>
	</div>
</div>

bulky/Areas/Admin/Views/User/Index.cshtml
@model List<Users>
<partial name="_Notification" />
@await Html.PartialAsync("_Notification")


<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-light ">Users List</h2>
			</div>
		</div>
	</div>

	<div class="card-body p-4">
		<div class="container">

			<div class="row  pb-3">
				<div class="col-2 text-end">
					<a class="btn btn-primary" asp-controller="HomeAdmin" asp-action="Index">
						back to home
					</a>
				</div>
				
			</div>

			<table class="table table-bordered  table-striped">
				<thead>
					<tr>
						<th>User Name</th>
						<th>E-mail</th>
						<th>Phone Number</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var obj in Model)
					{
						<tr>
							<td>@obj.UserName</td>
							<td>@obj.Email</td>
							<td>@obj.PhoneNumber</td>

							<td>
								<div class="w-75 btn-group" role="group">
									
									<a asp-controller="User" asp-action="Delete" asp-route-id="@obj.Id" class=" btn btn-danger mx-2">
										<i class="bi bi-trush-fill"></i> Delete
									</a>
								</div>
							</td>
						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>
</div>